// <auto-generated>
// Rewired Constants
// This list was generated on 9/19/2018 11:48:04 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // InGame
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game", friendlyName = "Move Horizontal")]
        public const int MoveHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game", friendlyName = "Move Vertical")]
        public const int MoveVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game", friendlyName = "Use Item")]
        public const int Item = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "In Game", friendlyName = "Change Witch")]
        public const int Switch = 3;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Horizontal Axis")]
        public const int UIHorizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Vertical Axis")]
        public const int UIVertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Submit")]
        public const int UISubmit = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UI Cancel")]
        public const int UICancel = 7;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int InGame = 1;
        public const int UI = 2;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int Player0 = 1;
            public const int Player1 = 2;
            public const int Player2 = 3;
            public const int Player3 = 4;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int Player2 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3")]
        public const int Player3 = 3;
    }
    public static partial class CustomController {
    }
}
